title: Portfolio
author: Myles 
description: >-
  A portfolio

url: "https://mylestym.github.io"
baseurl: "" # No subpath, since this is a user site

# Theme and plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate  # Add this to enable pagination plugin

# Minima-specific settings
minima:
  skin: dark
  social_links:
    github: mylestym
    linkedin: https://www.linkedin.com/in/myles-tym/
    twitter: your-twitter-handle  # Replace or remove

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM

# Other settings
permalink: pretty
future: true

paginate: 5
paginate_path: # _config.yml

plugins:
  - jekyll-paginate # Ensure this line is present if not already

paginate: 5 # Set to 5, so 5 projects are listed per page
paginate_path: "/page:num/" # This tells Jekyll to paginate from the root

# Post Display Settings
exclude:
  - README.md
  - LICENSE.txt
