title: Portfolio
author: Myles
description: >-
  A portfolio

url: "https://mylestym.github.io"
baseurl: ""

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

excerpt_separator: "<!--more-->"

markdown: kramdown
kramdown:
  input: GFM

permalink: pretty
future: true

exclude:
  - README.md
  - LICENSE.txt
